### ISSUE TITLE
As a client, I want my node be more secured in order to avoid unwanted connections

### ISSUE THREAD

**Issue by groussardaECL** [skillz-blockchain/volt_entity#19]
The node provisionned on AWS are placed into a fully open security group. This security group should be more restrictive.

Only the required inbound ports should be opened at first : 
* 8081 (for SkillZ service)
* 8545 (for blockchain RPC endpoint)
* 30303 (for blockchain IPC endpoint)

**Comment by noeRls** [comment]
The user can change the default ports. So either we do one security group by node deployed or we use only one security group with all traffic. The problem with creating one security group by node is kind of spam the aws security group section

**Comment by noeRls** [comment]
I think it would be interesting for security reason to don't open rpc and ipc port

**Comment by noeRls** [comment]
closing this issue cause of duplicate https://github.com/skillz-blockchain/baas_server/issues/19
