### ISSUE TITLE
Mount ebs volume as chain data

### ISSUE THREAD

**Issue by noeRls** [skillz-blockchain/volt_entity#45]

**Comment by noeRls** [comment]
> EBS supporte uniquement le montage d’un volume par une seule instance EC2

**Comment by noeRls** [comment]
Working like a charm. It's deeply integrated in k8s. You've just to make attention that the volume is:
- In the same **availability zone**
- Is formatted in **ext4**

**Comment by lucasclerisse** [comment]
> * same

All those problems have been addressed, the volume is formatted in **ext4** and you'll be able to chose the AZ when requesting the volume ID from the uservice
